/**
 * dsh-kiro pixel logo, generated by tools/logo.py — do not hand-edit.
 * Kiro ghost + DeepSeek whale, painted in code on true-pixel canvases
 * (fixed palette, pixel fonts, Bayer dithering) and packed to truecolor
 * half-block ANSI (upper-pixel fg + lower-pixel bg). Largest variant
 * that fits the terminal wins; callers fall back to ASCII otherwise.
 *
 * @module @damomoashidamomo/dsh-kiro/theme/logo-ansi
 */
export interface LogoVariant {
    readonly cols: number;
    readonly ansi: string;
}
/** Variants sorted widest-first. */
export declare const LOGO_VARIANTS: readonly LogoVariant[];
